# Day 2

For this part, you will be using Fox, not your own computer.
After logging in to Fox, choose on of the `int-` nodes
and log in to that.

::: {.callout-important}
If you have have not yet done what is written for [@sec-day1] of this module you have to do this first!
:::


## Using git on Fox

As we did on day 1, we need to enable the use of git:

<!-- FIXME update with latest version each year -->

```bash
module load git/2.49.0-GCCcore-14.2.0
```

Now run `git --version` to verify that you have access to `git`.


## Where to do the work

Start working in a folder such as `/fp/homes01/u01/ec-username/BIOS-IN5410`
replacing `ec-username` with your Educloud username.

## Getting started with git

Follow these lesson episodes:

NOTES
* If you are short on time, please skip the exercises,
these are marked with a pencil symbol at the left of the title.
* After today, **do not delete the `recipes` folder**, you will need it again
  for the next session

* [Creating a Repository](https://swcarpentry.github.io/git-novice/03-create.html)
  * NOTE here you are asked to make a folder on your Desktop, but we don't have that on Fox.
  Use `/fp/homes01/u01/ec-username/BIOS-IN5410` instead
(replacing `ec-username` with your Educloud username).
* [Tracking Changes](https://swcarpentry.github.io/git-novice/04-changes.html)
* [Exploring History](https://swcarpentry.github.io/git-novice/05-history.html)
* [Ignoring Things](https://swcarpentry.github.io/git-novice/06-ignore.html)

NOTES
* As mentioned, **do not delete the `recipes` folder**, you will need it again
  for the next session
